=== AndrewUru/astro-antfustyle-theme/src/blog-config-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema for blog-config.json",
  "description": "This schema defines the structure and constraints for the configuration of an Astro AntfuStyle Blog template, ensuring that all necessary fields are correctly specified and meet the requirements for proper blog functionality and styling",
  "type": "object",
  "properties": {
    "site": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the site."
        },
        "author": {
          "type": "string",
          "description": "The name of the author of the site."
        }
      },
      "required": ["name", "author"],
      "additionalProperties": false
    },
    "navBar": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "The order of the item configuration determines the order in which the navigation bar is displayed",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["text", "icon", "rwd"],
            "description": "The type of navigation item, which can be either 'text', 'icon', or 'both'. Selecting 'both' means showing text when the viewport width exceeds 768 pixels and icons otherwise."
          },
          "path": {
            "type": "string",
            "pattern": "^/.*",
            "description": "The URL the navigation item links to."
          },
          "prompt": {
            "type": "string",
            "description": "Show the role of the item when hovered over."
          },
          "text": {
            "type": "string",
            "description": "The text displayed for the navigation item; required if type is 'text' or 'rwd'."
          },
          "icon": {
            "type": "string",
            "description": "The icon name for the social media platform; required if type is 'icon' or 'rwd'."
          }
        },
        "allOf": [
          {
            "if": {
              "properties": { "type": { "const": "rwd" } }
            },
            "then": {
              "required": ["text", "icon"]
            }
          },
          {
            "if": {
              "properties": { "type": { "const": "icon" } }
            },
            "then": {
              "required": ["icon"]
            }
          },
          {
            "if": {
              "properties": { "type": { "const": "text" } }
            },
            "then": {
              "required": ["text"]
            }
          }
        ],
        "required": ["type", "path"],
        "additionalProperties": false
      }
    },
    "socials": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Show the social platform when hovered over."
          },
          "href": {
            "type": "string",
            "format": "uri",
            "description": "The URL to the social media profile."
          },
          "icon": {
            "type": "string",
            "examples": [
              "ri:twitter-x-fill",
              "ri-twitter-x-fill",
              "mdi:github",
              "mdi-github"
            ],
            "description": "The icon name for the social media platform. Check all available icons: https://icones.js.org/"
          },
          "rwd": {
            "type": "boolean",
            "description": "Whether the social media platform should be hidden on mobile devices."
          }
        },
        "required": ["name", "href", "icon"],
        "additionalProperties": false
      }
    },
    "metadata": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "The title of the page or section, typically used in SEO."
          },
          "description": {
            "type": "string",
            "description": "A brief description of the page or section, also typically used for SEO."
          }
        },
        "required": ["title", "description"]
      }
    }
  },
  "required": ["site", "metadata", "navBar", "socials"]
}

=== AndrewUru/astro-antfustyle-theme/src/blog-config.json
{
  "$schema": "./blog-config-schema.json",
  "site": {
    "name": "Astro AntfuStyle",
    "author": "Stephanie Lin"
  },
  "navBar": [
    {
      "type": "rwd",
      "path": "/blog",
      "prompt": "Blog",
      "text": "Blog",
      "icon": "ri-article-line"
    },
    {
      "type": "rwd",
      "path": "/projects",
      "prompt": "Projects",
      "text": "Projects",
      "icon": "ri-lightbulb-line"
    },
    {
      "type": "icon",
      "path": "/demos",
      "prompt": "Demos",
      "icon": "ri-screenshot-line"
    },
    {
      "type": "icon",
      "path": "/chat",
      "prompt": "Contact Me",
      "icon": "ri-chat-1-line"
    }
  ],
  "socials": [
    {
      "name": "Twitter",
      "href": "https://twitter.com/ASTRO_org",
      "icon": "ri-twitter-x-fill",
      "rwd": false
    },
    {
      "name": "Github Repo",
      "href": "https://github.com/lin-stephanie",
      "icon": "uil-github-alt",
      "rwd": false
    }
  ],
  "metadata": {
    "about": {
      "title": "About",
      "description": "About"
    },
    "blog": {
      "title": "Blog",
      "description": "Blog"
    },
    "projects": {
      "title": "Projects",
      "description": "List of projects that I am proud of"
    }
  }
}
